---
title: 'Week 1'
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: hide
  html_document:
    df_print: paged
    includes: /Users/hsubhash/Documents/GitHub/R Course/Common Assets/header.html
css: /Users/hsubhash/Documents/GitHub/R Course/Common Assets/curriculum.css
---
```{r, echo=FALSE, message=FALSE, error=FALSE}
library(fontawesome)
```

<div class="row">

<div class="col-sm-2 title">
###Learning Goals
</div>

<div class="col-sm-10 panelRow">
<div class="col-sm-3 learningGoal">

See through a machines eye

</div>

<div class="col-sm-3 learningGoal">

Master data types and structures

</div>

<div class="col-sm-3 learningGoal">

Subset data structures

</div>

<div class="col-sm-3 learningGoal">

Compose code with pipes

</div>

</div>
</div>


<div class="row">

<div class="col-sm-2 title">
###Pre-requisites
</div>

<div class="col-sm-10 panelRow">
<div class="col-sm-6">

####`r fa("save", fill="grey")` Install fest (`r fa("stopwatch", fill="grey")`: 1 hr)

1. Create accounts at [Github](https://github.com/); [Zoom](https://zoom.us/signup) is optional.
2. Install [R](https://cran.r-project.org/), [Rstudio](https://www.rstudio.com/products/rstudio/download/), [Slack](https://slack.com/downloads), [Zoom](https://zoom.us/download#client_4meeting) and [Github desktop](https://desktop.github.com/)
3. Join the [Slack workspace](https://get.slack.help/hc/en-us/articles/212675257-Join-a-Slack-workspace)  for this course.[^1]

[^1]: An email will be sent to you requesting you to join after you sign-up.

</div>
<div class="col-sm-6">

####`r fa("book-open", fill="grey")` Reading list
1. [R for cats](https://rforcats.net/) (`r fa("stopwatch", fill="grey")`: 2 hrs)
2. [Benefits of version control](https://www.atlassian.com/git/tutorials/what-is-version-control) (`r fa("stopwatch", fill="grey")`: 1 hr)

</div>
</div>
</div>


<div class="row">

<div class="col-sm-2 title">
###Topics
</div>

<div class="col-sm-10 panelRow">
<div class="col-sm-6">
####`r fa("chalkboard-teacher", fill="grey")` Class 1 (`r fa("stopwatch", fill="grey")`: 3 hrs)

0. Introductions and housekeeping
1. What is programming?
2. Variables in R
3. Create vectors using `c()`, `seq()` and `paste()`
4. R Studio
    + The different parts
    + The many ways to write R code
    + R notebook deep dive
5. Data types
    + Character, numeric, integer, boolean
    + Factor
6. Data structures
7. Subset vectors and data frames using indices
8. Operators in R
9. Basic arithmetic and logical operations
</div>

<div class="col-sm-6">
####`r fa("chalkboard-teacher", fill="grey")` Class 2 (`r fa("stopwatch", fill="grey")`: 3 hrs)

1. Class 1 Revision
2. Advanced subsetting
    + Using logical operators
    + Lists
5. Functions
    + How do we call them?
    + How do we assign parameters?
6. Packages
6. Introduction to [Tidyverse](https://www.tidyverse.org/)
7. Compose operations using pipes
8. Week 1 Assignment
</div>
</div>
</div>