---
title: 'Week 2'
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: hide
  html_document:
    df_print: paged
    includes: /Users/hsubhash/Documents/GitHub/R Course/Common Assets/header.html
css: /Users/hsubhash/Documents/GitHub/R Course/Common Assets/curriculum.css
---

```{r, echo=FALSE, message=FALSE, error=FALSE}
library(fontawesome)
```


<div class="row">

<div class="col-sm-2 title">
###Learning Goals
</div>

<div class="col-sm-10 panelRow">
<div class="col-sm-3 learningGoal">
Master the 5 dplyr verbs
</div>
<div class="col-sm-3 learningGoal">
Master the 5 dplyr verbs
</div>
<div class="col-sm-3 learningGoal">
Master the 5 dplyr verbs
</div>
<div class="col-sm-3 learningGoal">
Master the 5 dplyr verbs
</div>
</div>
</div>

<div class="row">

<div class="col-sm-2 title">
###Pre-requisites
</div>

<div class="col-sm-10 panelRow">
####`r fa("book-open", fill="grey")` Reading list
1. [The tidy tools manifesto](https://cran.r-project.org/web/packages/tidyverse/vignettes/manifesto.html) (`r fa("stopwatch", fill="grey")`: 0.2 hr)
2. [Benefits of version control](https://www.atlassian.com/git/tutorials/what-is-version-control) (`r fa("stopwatch", fill="grey")`: 1 hr)
<!-- <div class="col-sm-6"> -->
<!-- </div> -->
<!-- <div class="col-sm-6"> -->
<!-- </div> -->
</div>
</div>

<div class="row">

<div class="col-sm-2 title">
###Topics
</div>

<div class="col-sm-10 panelRow">
<div class="col-sm-6">
####`r fa("chalkboard-teacher", fill="grey")` Class 1 (`r fa("stopwatch", fill="grey")`: 3 hrs)

1. Introduction to dplyr
2. Tibbles
3. Whats .data?
4. R Studio
    + The different parts
    + The many ways to write R code
    + R notebook deep dive
5. Data types
    + Character, numeric, integer, boolean
    + Factor
6. Data structures
7. Subset vectors and data frames using indices
</div>
<div class="col-sm-6">
####`r fa("chalkboard-teacher", fill="grey")` Class 2 (`r fa("stopwatch", fill="grey")`: 3 hrs)

0. Introductions and housekeeping
1. What is programming?
2. Variables in R
3. Create vectors using `c()`, `seq()` and `paste()`
4. R Studio
    + The different parts
    + The many ways to write R code
    + R notebook deep dive
5. Data types
    + Character, numeric, integer, boolean
    + Factor
6. Data structures
7. Subset vectors and data frames using indices
</div>
</div>
</div>
